In [ ]:
# #@title Mount Drive
# from google.colab import drive
# drive.mount('/content/drive')
# !pip3 install numpy
# %cd /content/drive/My Drive

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
/content/drive/My Drive


In [2]:
# !pip3 install numpy
import numpy as np

# Recitation
## *Using Vectors and Arrays in NumPy*

## Authors
> Joseph Konan <jkonan@andrew.cmu.edu\>, 11-785 TA <br>
> Modified by 10601 Course Staff

## Reference
> Kelly, Piares A. "[7.1 Vectors, Tensors and the Index Notation.](http://homepages.engineering.auckland.ac.nz/~pkel015/SolidMechanicsBooks/Part_II/07_3DElasticity/07_3DElasticity_01_3D_Index.pdf)" In Solid Mechanics Part II: Engineering Solid Mechanics, 189-200. 2012.

> A nice cheat sheet: https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf

## Command Line, File I/O, and Google Colab Tutorial
> https://docs.google.com/document/d/1RSGvlBG8dDfs62_0jJEHnQFN-Au6yFbp8M6QTNs3EIY/edit?usp=sharing

## Table of Contents
1. Setting-up NumPy
2. Loading TSV Files
3. Slicing and Indexing Arrays
4. Vectors vs Arrays
5. Useful Numpy Functions

## 1. Setting-up NumPy
### Installing NumPy
To install NumPy using pip:
> `pip install numpy`

To upgrade NumPy using pip:
> `pip install numpy --upgrade`

To see current version of NumPy:
> `pip show numpy`

Alternative methods can be found here:

> https://scipy.org/install.html

### Importing NumPy
We import NumPy similar to how to import any other python library.

In [3]:
import numpy as np
np.random.seed(0)

np.version.version

'1.24.3'

##2. Loading TSV Files
There are many ways to load a TSV (or any delimited) file. The easiest way is `np.genfromtxt()`.



In [4]:
f = "small_train.tsv"

In [8]:
data = np.genfromtxt(f, delimiter="\t", dtype=None, encoding=None, skip_header=0)
print(data)
title = data[0, 0:2]
data = data[1:]
print(title)
print(data)

[['title1' 'title2']
 ['1' '2']
 ['3' '4']]
['title1' 'title2']
[['1' '2']
 ['3' '4']]


##3. Slicing and Indexing Arrays
Rows and columns of an array can be selected in the form
> `array[r,c]`

Where the `r` is the row index and `c` is the column index

$
\left[
  \begin{array}{cc}
  [1 & 2 & 3] \\
  [4 & 5 & 6] \\
  [7 & 8 & 9]
  \end{array}
\right]
$

In [9]:
data = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("1st row, 1st col: ", data[0, 0])

1st row, 1st col:  1


In [10]:
data * data

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

If you want to capture multiple consecutive rows/cols at once, use `x:y`. It means "from x (included) until y (not included)". First and last indices can be left blank

In [11]:
print("Row 0: ", data[0,0:3])
data[0]
print("Col 0: ", data[:,0])

Row 0:  [1 2 3]
Col 0:  [1 4 7]


In [12]:
print("First two rows: ", data[:2,:])
print("Rows after first 2 rows: ", data[2:,:])

First two rows:  [[1 2 3]
 [4 5 6]]
Rows after first 2 rows:  [[7 8 9]]


You can also take non-consecutive sections, using index lists

In [13]:
print("Rows 0,2: ", data[ [0,2] , :])

Rows 0,2:  [[1 2 3]
 [7 8 9]]


In order to find the size of your array, use the `.shape` feature. It returns a list of the number of rows and columns

In [14]:
print(data.shape)
print("Number of rows: ", data.shape[0])
print("Number of cols: ", data.shape[1])
print("Array Dimension: ", data.shape)
print("Number of Rows: ", len(data))
print("Number of Cols: ", len(data[0]))
print("Number of Elements: ", data.size)

(3, 3)
Number of rows:  3
Number of cols:  3
Array Dimension:  (3, 3)
Number of Rows:  3
Number of Cols:  3
Number of Elements:  9


##4. Vectors vs Arrays
Numpy vectors differ from arrays in that they are 1D. Certain differences in indexing may cause an issue

In [ ]:
x = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10,11,12],
              [13,14,15,16]]
             )
v = np.array([[[1,2,3,4]]])
print(v.shape)
y = x[0,:]
y1 = x[:,0]
print(x)
print(y)
print(y1)
print(y.shape)
print(y1.shape)

(1, 1, 4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[1 2 3 4]
[ 1  5  9 13]
(4,)
(4,)


In [ ]:
y.reshape((2, -1))

array([[1, 2],
       [3, 4]])

In [ ]:
y2 = y.reshape([1, y.shape[0]])
print(y2)

[[1 2 3 4]]


Notice that vectors and arrays have different dimensions

In [ ]:
print(y.shape)
print(y2.shape)

(4,)
(1, 4)


Vectors also cannot be transposed

In [ ]:
print(y.T)
print(y2.T)

[1 2 3 4]
[[1]
 [2]
 [3]
 [4]]


In [ ]:
v = np.array([1,2,3,4])
w = np.array([1,1,1,1])
print(np.dot(v,w))

10


##5. Useful Numpy Functions
There are many common functions that we believe will be very useful throughout your assignments. They're organized into type below:

In [ ]:
z = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

## Initializations
1. Identity Matrix

In [ ]:
i4 = np.eye(4)
print(i4)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


2. Matrix of 0s or 1s

In [ ]:
zeros = np.zeros([2,3])
ones = np.ones((2,3))

print(zeros)
print(ones)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


3. Random Initializations with np.random (more documentation at: https://docs.scipy.org/doc/numpy-1.15.0/reference/routines.random.html)

In [ ]:
#Random number between 0 and 1
random = np.random.random((2,3))
print(random)

[[0.5488135  0.71518937 0.60276338]
 [0.54488318 0.4236548  0.64589411]]


In [ ]:
#Random decimal between given range
uniform = np.random.uniform(low=-0.1, high=0.1, size=(2,3))
print(uniform)

[[-0.01248256  0.0783546   0.09273255]
 [-0.0233117   0.05834501  0.00577898]]


In [ ]:
#Random integer between given range
integer = np.random.randint(low=-20, high=20, size=(2,3))
print(integer)

[[  4  -3  17]
 [  5  -7 -12]]


## Reshaping arrays

In [ ]:
print(x)
print(x.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
(4, 4)


In [ ]:
print(x.reshape([4,-1]))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [ ]:
nrows = 1
print(x.reshape([nrows, -1]))

[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]]


In [ ]:
print(y)
print(y.shape)

[[5 6]
 [7 8]]
(2, 2)


In [ ]:
print(y.reshape([4,1]))

[[5]
 [6]
 [7]
 [8]]


3. Appending arrays with vstack/hstack

$$
\left[\begin{array}{cc}
[1 & 2] \\
[3 & 4]
\end{array}\right]
hstack
\left[\begin{array}{cc}
[5 & 6] \\
[7 & 8]
\end{array}\right]
=
\left[\begin{array}{cc}
[1 & 2 & 5 & 6] \\
[3 & 4 & 7 & 8]
\end{array}\right]
$$

In [ ]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
h_stack = np.hstack([x, y])
print(h_stack)

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
x = np.array([1,2,3])
print(x)
y = np.array([4,5,6])
print(y)
x.dot(y)

[1 2 3]
[4 5 6]


32

$$
\left[\begin{array}{cc}
[1 & 2] \\
[3 & 4]
\end{array}\right]
vstack
\left[\begin{array}{cc}
[5 & 6] \\
[7 & 8]
\end{array}\right]
=
\left[\begin{array}{cc}
[1 & 2]\\
[3 & 4]\\
[5 & 6]\\
[7 & 8]
\end{array}\right]
$$

In [ ]:
v_stack = np.vstack([x, y])
print(v_stack)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


## Matrix Operations
For the next couple of cells, we will be using

$$ x =
\left[\begin{array}{cc}
[1 & 2] \\
[3 & 4]
\end{array}\right]
$
and
$ y =
\left[\begin{array}{cc}
[5 & 6] \\
[7 & 8]
\end{array}\right]
$
1. Addition

$
\left(\begin{array}{cc}
1 & 2 \\
3 & 4
\end{array}\right)
+
\left(\begin{array}{cc}
5 & 6 \\
7 & 8
\end{array}\right)
=
\left(\begin{array}{cc}
6 & 8 \\
10 & 12
\end{array}\right)
$$

In [ ]:
add_v1 = np.add(x, y)
add_v2 = x + y
print("Are both the same? ",np.array_equal(add_v1, add_v2))
print(add_v1)

Are both the same?  True
[[ 6  8]
 [10 12]]


2. Subtraction

$$
\left(\begin{array}{cc}
5 & 6 \\
7 & 8
\end{array}\right)
-
\left(\begin{array}{cc}
1 & 2 \\
3 & 4
\end{array}\right)
=
\left(\begin{array}{cc}
4 & 4 \\
4 & 4
\end{array}\right)
$$

In [ ]:
sub = y - x
print(sub)

[[4 4]
 [4 4]]


3. Multiplying by a Constant

$$
4 *
\left(\begin{array}{cc}
1 & 2 \\
3 & 4
\end{array}\right)
=
\left(\begin{array}{cc}
4 & 8 \\
12 & 16
\end{array}\right)
$$

In [ ]:
c = 4
print(c * x)

# broadcasting

[[ 4  8]
 [12 16]]


4. Matrix Multiplication

$$
\left(\begin{array}{cc}
1 & 2 \\
3 & 4 \\
5 & 6
\end{array}\right)
\cdot
\left(\begin{array}{cc}
5 & 6 & 7\\
8 & 9 & 10
\end{array}\right)
=
\begin{pmatrix}21&24&27\\ 47&54&61\\ 73&84&95\end{pmatrix}
$$

In [ ]:
l = np.array([[1,2],[3,4],[5,6]])
r = np.array([[5,6,7],[8,9,10]])
print(l)
print(r)

[[1 2]
 [3 4]
 [5 6]]
[[5 6 7]]


In [ ]:
mult_v1 = np.matmul(l, r)
mult_v2 = l @ r
print("Are both the same? ", np.array_equal(mult_v1, mult_v2))
print(mult_v1)

Are both the same?  True
[[21 24 27]
 [47 54 61]]


5. Elementwise multiplication

$$
\left(\begin{array}{cc}
1 & 2 \\
3 & 4
\end{array}\right)
\times
\left(\begin{array}{cc}
5 & 6 \\
7 & 8
\end{array}\right)
=
\left(\begin{array}{cc}
5 & 12 \\
21 & 32
\end{array}\right)
$$

In [ ]:
elem_mult = x * y
print(elem_mult)

[[ 5 12]
 [21 32]]


## Math Operations

1. Exponential and natural log

In [ ]:
print(np.exp(x))

print("exp(1) = ", np.exp(1))
print("exp(2) = ", np.exp(2))
print("exp(3) = ", np.exp(3))
print("exp(4) = ", np.exp(4))

[[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]]
exp(1) =  2.718281828459045
exp(2) =  7.38905609893065
exp(3) =  20.085536923187668
exp(4) =  54.598150033144236


In [ ]:
print(np.log(x))

print("log(1) = ", np.log(1))
print("log(2) = ", np.log(2))
print("log(3) = ", np.log(3))
print("log(4) = ", np.log(4))

[[0.         0.69314718]
 [1.09861229 1.38629436]]
log(1) =  0.0
log(2) =  0.6931471805599453
log(3) =  1.0986122886681098
log(4) =  1.3862943611198906


2. Min/Max, Argmin/Argmax, maximum/minimum

In [ ]:
wide_df = np.hstack([x,y])
print(wide_df)
print("Max of first row is: ", np.max(wide_df[0,:]))
print("It is in column: ", np.argmax(wide_df[0,:]))

[[1 2 5 6]
 [3 4 7 8]]
Max of first row is:  6
It is in column:  3


In [ ]:
long_df = np.vstack([x,y])
print(long_df)
print("Min of 2nd col is: ", np.min(long_df[:,1]))
print("It is in row: ", np.argmin(long_df[:,1]))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Min of 2nd col is:  2
It is in row:  0


In [ ]:
a = np.array([2,4,5])
b = np.array([3,1,6])
print("Element wise maximum of a and b is: ", np.maximum(a, b))
print("Element wise minimum of a and b is: ", np.minimum(a, b))

Element wise maximum of a and b is:  [3 4 6]
Element wise minimum of a and b is:  [2 1 5]


In [ ]:
a = np.array([
              [1,2],
              [3,4],
              [5,6]
])
# a used to be 3x2
print(a.sum(axis=0)) # a becomes 2
print(a.sum(axis=1)) # a become 3
print(a.sum())
#a / a.sum(axis=0)
print(a*(1/a.sum(axis=0)))

[ 9 12]
[ 3  7 11]
21
[[0.11111111 0.16666667]
 [0.33333333 0.33333333]
 [0.55555556 0.5       ]]
